@server=http://localhost:4004
@username=alice
@password=


### Regions
# @name Regions_GET
GET {{server}}/odata/v4/catalog/Regions
Authorization: Basic {{username}}:{{password}}


### Regions
# @name Regions_POST
POST {{server}}/odata/v4/catalog/Regions
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "17666249-a02e-4b0d-9935-ef15e0cc0482",
  "regionName": "regionName-17666249",
  "country": "country-17666249",
  "createdAt": "2001-12-25T00:00:00.000Z",
  "createdBy": "createdBy.aind5@example.net",
  "modifiedAt": "2019-07-13T00:00:00.000Z",
  "modifiedBy": "modifiedBy.aind5@example.net"
}


### Regions
# @name Regions_PATCH
PATCH {{server}}/odata/v4/catalog/Regions/17666249-a02e-4b0d-9935-ef15e0cc0482
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "17666249-a02e-4b0d-9935-ef15e0cc0482",
  "regionName": "regionName-17666249",
  "country": "country-17666249",
  "createdAt": "2001-12-25T00:00:00.000Z",
  "createdBy": "createdBy.aind5@example.net",
  "modifiedAt": "2019-07-13T00:00:00.000Z",
  "modifiedBy": "modifiedBy.aind5@example.net"
}


### Regions
# @name Regions_DELETE
DELETE {{server}}/odata/v4/catalog/Regions/17666249-a02e-4b0d-9935-ef15e0cc0482
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Employees
# @name Employees_GET
GET {{server}}/odata/v4/catalog/Employees
Authorization: Basic {{username}}:{{password}}


### Employees
# @name Employees_POST
POST {{server}}/odata/v4/catalog/Employees
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "17594194-3cf2-41b0-899c-00bec7b04345",
  "employeeId": "d-17594194",
  "firstName": "firstName-17594194",
  "lastName": "lastName-17594194",
  "email": "email-17594194",
  "designation": "designation-17594194",
  "salary": 135060353909.27,
  "joiningDate": "2009-02-23",
  "region": {
    "ID": "17666249-a02e-4b0d-9935-ef15e0cc0482"
  },
  "createdAt": "2004-03-30T00:00:00.000Z",
  "createdBy": "createdBy.ah3rm@example.com",
  "modifiedAt": "2010-04-15T00:00:00.000Z",
  "modifiedBy": "modifiedBy.ah3rm@example.com"
}


### Employees
# @name Employees_PATCH
PATCH {{server}}/odata/v4/catalog/Employees/17594194-3cf2-41b0-899c-00bec7b04345
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "17594194-3cf2-41b0-899c-00bec7b04345",
  "employeeId": "d-17594194",
  "firstName": "firstName-17594194",
  "lastName": "lastName-17594194",
  "email": "email-17594194",
  "designation": "designation-17594194",
  "salary": 135060353909.27,
  "joiningDate": "2009-02-23",
  "region": {
    "ID": "17666249-a02e-4b0d-9935-ef15e0cc0482"
  },
  "createdAt": "2004-03-30T00:00:00.000Z",
  "createdBy": "createdBy.ah3rm@example.com",
  "modifiedAt": "2010-04-15T00:00:00.000Z",
  "modifiedBy": "modifiedBy.ah3rm@example.com"
}


### Employees
# @name Employees_DELETE
DELETE {{server}}/odata/v4/catalog/Employees/17594194-3cf2-41b0-899c-00bec7b04345
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_GET
GET {{server}}/odata/v4/catalog/Orders
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_POST
POST {{server}}/odata/v4/catalog/Orders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "13286025-9d08-4407-8501-e02438032fa3",
  "orderNumber": "orderNumber-13286025",
  "orderDate": "2015-04-17",
  "status": "status-13286025",
  "totalAmount": 5939771595614.17,
  "discountAmount": 4602178994606.3,
  "netAmount": 590288665771.02,
  "customer": {
    "ID": "10366401-75db-4580-9c16-2d042f56d95b"
  },
  "salesEmployee": {
    "ID": "17594194-3cf2-41b0-899c-00bec7b04345"
  },
  "items": [
    {
      "ID": "11897652-896a-4d0f-9417-44d9721a97d6",
      "product": {
        "ID": "15382332-1a93-42da-86a0-c904d039fa56"
      },
      "quantity": 46,
      "sellingPrice": 1971166404179.85,
      "discount": 483.36,
      "lineAmount": 8665439602471.53
    },
    {
      "ID": "11897653-486a-4e7d-84e6-11abeba033cf",
      "product": {
        "ID": "15382332-1a93-42da-86a0-c904d039fa56"
      },
      "quantity": 83,
      "sellingPrice": 7702686831255.18,
      "discount": 779.94,
      "lineAmount": 4593849010806.33
    }
  ],
  "createdAt": "2018-01-27T00:00:00.000Z",
  "createdBy": "createdBy.7wrk9@example.net",
  "modifiedAt": "2000-11-12T00:00:00.000Z",
  "modifiedBy": "modifiedBy.7wrk9@example.net"
}


### Orders
# @name Orders_PATCH
PATCH {{server}}/odata/v4/catalog/Orders/13286025-9d08-4407-8501-e02438032fa3
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "13286025-9d08-4407-8501-e02438032fa3",
  "orderNumber": "orderNumber-13286025",
  "orderDate": "2015-04-17",
  "status": "status-13286025",
  "totalAmount": 5939771595614.17,
  "discountAmount": 4602178994606.3,
  "netAmount": 590288665771.02,
  "customer": {
    "ID": "10366401-75db-4580-9c16-2d042f56d95b"
  },
  "salesEmployee": {
    "ID": "17594194-3cf2-41b0-899c-00bec7b04345"
  },
  "items": [
    {
      "ID": "11897652-896a-4d0f-9417-44d9721a97d6",
      "product": {
        "ID": "15382332-1a93-42da-86a0-c904d039fa56"
      },
      "quantity": 46,
      "sellingPrice": 1971166404179.85,
      "discount": 483.36,
      "lineAmount": 8665439602471.53
    },
    {
      "ID": "11897653-486a-4e7d-84e6-11abeba033cf",
      "product": {
        "ID": "15382332-1a93-42da-86a0-c904d039fa56"
      },
      "quantity": 83,
      "sellingPrice": 7702686831255.18,
      "discount": 779.94,
      "lineAmount": 4593849010806.33
    }
  ],
  "createdAt": "2018-01-27T00:00:00.000Z",
  "createdBy": "createdBy.7wrk9@example.net",
  "modifiedAt": "2000-11-12T00:00:00.000Z",
  "modifiedBy": "modifiedBy.7wrk9@example.net"
}


### Orders
# @name Orders_DELETE
DELETE {{server}}/odata/v4/catalog/Orders/13286025-9d08-4407-8501-e02438032fa3
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Customers
# @name Customers_GET
GET {{server}}/odata/v4/catalog/Customers
Authorization: Basic {{username}}:{{password}}


### Customers
# @name Customers_POST
POST {{server}}/odata/v4/catalog/Customers
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "10366401-75db-4580-9c16-2d042f56d95b",
  "customerNo": "omerNo-10366401",
  "customerName": "customerName-10366401",
  "email": "email-10366401",
  "phone": "phone-10366401",
  "city": "city-10366401",
  "tier": "tier-10366401",
  "lifetimeRevenue": 4565166915012.98,
  "totalOrders": 79,
  "lastTierUpdate": "2009-10-10T00:00:00.000Z",
  "region": {
    "ID": "17666249-a02e-4b0d-9935-ef15e0cc0482"
  },
  "orders": [
    {
      "ID": "73519497-a2a2-49d1-9061-6750b0422973",
      "orderNumber": "orderNumber-7351949",
      "orderDate": "2000-07-28",
      "status": "status-7351949",
      "totalAmount": 1755295860606.53,
      "discountAmount": 1180148070977.09,
      "netAmount": 4103913849292.26,
      "salesEmployee": {
        "ID": "17594194-3cf2-41b0-899c-00bec7b04345"
      },
      "items": [
        {
          "ID": "29623386-63dc-4999-88b6-799ccaaa7275",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 20,
          "sellingPrice": 6023320366978.52,
          "discount": 57.83,
          "lineAmount": 2498525596958.37
        },
        {
          "ID": "29623387-d7d8-4af1-856f-328661ba362d",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 48,
          "sellingPrice": 6605321534416.23,
          "discount": 417.77,
          "lineAmount": 9560510507883.92
        }
      ],
      "createdAt": "2014-07-27T00:00:00.000Z",
      "createdBy": "createdBy.4dkst@example.net",
      "modifiedAt": "2008-07-27T00:00:00.000Z",
      "modifiedBy": "modifiedBy.4dkst@example.net"
    },
    {
      "ID": "73519508-3d33-41be-9f89-4414bcddff66",
      "orderNumber": "orderNumber-7351950",
      "orderDate": "2019-12-15",
      "status": "status-7351950",
      "totalAmount": 1832304702492.12,
      "discountAmount": 7114802213473.49,
      "netAmount": 9287579779838.69,
      "salesEmployee": {
        "ID": "17594194-3cf2-41b0-899c-00bec7b04345"
      },
      "items": [
        {
          "ID": "10425545-a4e4-4a11-b65e-7dd8bd8e0f08",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 59,
          "sellingPrice": 594797789950.01,
          "discount": 625.79,
          "lineAmount": 7764956048627.14
        },
        {
          "ID": "10425546-2f2a-4cc0-af14-c0f793af0987",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 47,
          "sellingPrice": 6654483198603.94,
          "discount": 510.33,
          "lineAmount": 3652275716704.88
        }
      ],
      "createdAt": "2012-05-25T00:00:00.000Z",
      "createdBy": "createdBy.4dksu@example.net",
      "modifiedAt": "2012-07-17T00:00:00.000Z",
      "modifiedBy": "modifiedBy.4dksu@example.com"
    }
  ],
  "createdAt": "2015-10-02T00:00:00.000Z",
  "createdBy": "createdBy.666rl@example.com",
  "modifiedAt": "2022-04-05T00:00:00.000Z",
  "modifiedBy": "modifiedBy.666rl@example.com"
}


### Customers
# @name Customers_PATCH
PATCH {{server}}/odata/v4/catalog/Customers/10366401-75db-4580-9c16-2d042f56d95b
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "10366401-75db-4580-9c16-2d042f56d95b",
  "customerNo": "omerNo-10366401",
  "customerName": "customerName-10366401",
  "email": "email-10366401",
  "phone": "phone-10366401",
  "city": "city-10366401",
  "tier": "tier-10366401",
  "lifetimeRevenue": 4565166915012.98,
  "totalOrders": 79,
  "lastTierUpdate": "2009-10-10T00:00:00.000Z",
  "region": {
    "ID": "17666249-a02e-4b0d-9935-ef15e0cc0482"
  },
  "orders": [
    {
      "ID": "73519497-a2a2-49d1-9061-6750b0422973",
      "orderNumber": "orderNumber-7351949",
      "orderDate": "2000-07-28",
      "status": "status-7351949",
      "totalAmount": 1755295860606.53,
      "discountAmount": 1180148070977.09,
      "netAmount": 4103913849292.26,
      "salesEmployee": {
        "ID": "17594194-3cf2-41b0-899c-00bec7b04345"
      },
      "items": [
        {
          "ID": "29623386-63dc-4999-88b6-799ccaaa7275",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 20,
          "sellingPrice": 6023320366978.52,
          "discount": 57.83,
          "lineAmount": 2498525596958.37
        },
        {
          "ID": "29623387-d7d8-4af1-856f-328661ba362d",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 48,
          "sellingPrice": 6605321534416.23,
          "discount": 417.77,
          "lineAmount": 9560510507883.92
        }
      ],
      "createdAt": "2014-07-27T00:00:00.000Z",
      "createdBy": "createdBy.4dkst@example.net",
      "modifiedAt": "2008-07-27T00:00:00.000Z",
      "modifiedBy": "modifiedBy.4dkst@example.net"
    },
    {
      "ID": "73519508-3d33-41be-9f89-4414bcddff66",
      "orderNumber": "orderNumber-7351950",
      "orderDate": "2019-12-15",
      "status": "status-7351950",
      "totalAmount": 1832304702492.12,
      "discountAmount": 7114802213473.49,
      "netAmount": 9287579779838.69,
      "salesEmployee": {
        "ID": "17594194-3cf2-41b0-899c-00bec7b04345"
      },
      "items": [
        {
          "ID": "10425545-a4e4-4a11-b65e-7dd8bd8e0f08",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 59,
          "sellingPrice": 594797789950.01,
          "discount": 625.79,
          "lineAmount": 7764956048627.14
        },
        {
          "ID": "10425546-2f2a-4cc0-af14-c0f793af0987",
          "product": {
            "ID": "15382332-1a93-42da-86a0-c904d039fa56"
          },
          "quantity": 47,
          "sellingPrice": 6654483198603.94,
          "discount": 510.33,
          "lineAmount": 3652275716704.88
        }
      ],
      "createdAt": "2012-05-25T00:00:00.000Z",
      "createdBy": "createdBy.4dksu@example.net",
      "modifiedAt": "2012-07-17T00:00:00.000Z",
      "modifiedBy": "modifiedBy.4dksu@example.com"
    }
  ],
  "createdAt": "2015-10-02T00:00:00.000Z",
  "createdBy": "createdBy.666rl@example.com",
  "modifiedAt": "2022-04-05T00:00:00.000Z",
  "modifiedBy": "modifiedBy.666rl@example.com"
}


### Customers
# @name Customers_DELETE
DELETE {{server}}/odata/v4/catalog/Customers/10366401-75db-4580-9c16-2d042f56d95b
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### OrderItems
# @name OrderItems_GET
GET {{server}}/odata/v4/catalog/OrderItems
Authorization: Basic {{username}}:{{password}}


### OrderItems
# @name OrderItems_POST
POST {{server}}/odata/v4/catalog/OrderItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "29623386-63dc-4999-88b6-799ccaaa7275",
  "product": {
    "ID": "15382332-1a93-42da-86a0-c904d039fa56"
  },
  "quantity": 20,
  "sellingPrice": 6023320366978.52,
  "discount": 57.83,
  "lineAmount": 2498525596958.37
}


### OrderItems
# @name OrderItems_PATCH
PATCH {{server}}/odata/v4/catalog/OrderItems/29623386-63dc-4999-88b6-799ccaaa7275
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "29623386-63dc-4999-88b6-799ccaaa7275",
  "product": {
    "ID": "15382332-1a93-42da-86a0-c904d039fa56"
  },
  "quantity": 20,
  "sellingPrice": 6023320366978.52,
  "discount": 57.83,
  "lineAmount": 2498525596958.37
}


### OrderItems
# @name OrderItems_DELETE
DELETE {{server}}/odata/v4/catalog/OrderItems/29623386-63dc-4999-88b6-799ccaaa7275
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Products
# @name Products_GET
GET {{server}}/odata/v4/catalog/Products
Authorization: Basic {{username}}:{{password}}


### Products
# @name Products_POST
POST {{server}}/odata/v4/catalog/Products
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15382332-1a93-42da-86a0-c904d039fa56",
  "productCode": "productCode-15382332",
  "productName": "productName-15382332",
  "category": "category-15382332",
  "unitPrice": 220533244846.02,
  "costPrice": 784030575437.68,
  "stock": 49,
  "createdAt": "2003-01-02T00:00:00.000Z",
  "createdBy": "createdBy.95p30@example.org",
  "modifiedAt": "2010-04-30T00:00:00.000Z",
  "modifiedBy": "modifiedBy.95p30@example.org"
}


### Products
# @name Products_PATCH
PATCH {{server}}/odata/v4/catalog/Products/15382332-1a93-42da-86a0-c904d039fa56
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15382332-1a93-42da-86a0-c904d039fa56",
  "productCode": "productCode-15382332",
  "productName": "productName-15382332",
  "category": "category-15382332",
  "unitPrice": 220533244846.02,
  "costPrice": 784030575437.68,
  "stock": 49,
  "createdAt": "2003-01-02T00:00:00.000Z",
  "createdBy": "createdBy.95p30@example.org",
  "modifiedAt": "2010-04-30T00:00:00.000Z",
  "modifiedBy": "modifiedBy.95p30@example.org"
}


### Products
# @name Products_DELETE
DELETE {{server}}/odata/v4/catalog/Products/15382332-1a93-42da-86a0-c904d039fa56
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesAnalytics
# @name SalesAnalytics_GET
GET {{server}}/odata/v4/catalog/SalesAnalytics


### updateCustomerTier
# @name updateCustomerTier_POST
POST {{server}}/odata/v4/catalog/updateCustomerTier
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### refreshAnalytics
# @name refreshAnalytics_POST
POST {{server}}/odata/v4/catalog/refreshAnalytics
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}
